### ISSUE TITLE
SELF_SIGNED_CERT_IN_CHAIN problem

### ISSUE THREAD

**Issue by peacemoon** [danger/swift#200]
I'm starting to integrate Danger with our Bitbucket Server. I'm seeing this issue when call `danger-swift pr https://bitbucket.server/pr/50`

```
Error:  { FetchError: request to xxxxx failed, reason: self signed certificate in certificate chain
    at ClientRequest.<anonymous> (/snapshot/danger-js/node_modules/node-fetch/lib/index.js:1444:11)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:382:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  message:
   'request to xxxxx failed, reason: self signed certificate in certificate chain',
  type: 'system',
  errno: 'SELF_SIGNED_CERT_IN_CHAIN',
  code: 'SELF_SIGNED_CERT_IN_CHAIN' }
```

Anyone knows how to resolve?

**Comment by peacemoon** [comment]
ok I saw this in source code of danger-js https://github.com/danger/danger-js/blob/258cde31bed5047f68a9f5c9f9ebc425a567c896/source/platforms/bitbucket_server/BitBucketServerAPI.ts#L346
