### ISSUE TITLE
Bitrise ENV set https URL faling 

### ISSUE THREAD

**Issue by Smitesh-P** [danger/swift#396]
I am setting GIT_REPOSITORY HTTPS URL as bitrise build process and set it in bitrise env variable.

After that running danger-swift get the proper url but it cannot decode url. Thats why it is failing as unauthorized url.

Error:  HTTPError: Unauthorized
    at fn (/snapshot/danger-js/node_modules/ky/umd.js:251:12)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Ky._retry (/snapshot/danger-js/node_modules/ky/umd.js:319:12) {
  name: 'HTTPError',
  response: Response {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://gitlab.com/api/v4/projects/https%3A%2F%2F[REDACTED]%3A[REDACTED]%40gitlab.project_domain.com%2Fios%2Fproject_name/merge_requests/1234/changes',
      status: 401,
      statusText: 'Unauthorized',
      headers: [Headers]
    }
  },
  description: '401 Unauthorized'
}

is there any way i can set this decoded URL.

**Comment by orta** [comment]
This feels like it needs more info to be understood, can you write a more detailed issue please?

**Comment by pavank30** [comment]
@Smitesh-P how did u resolve this issue. Even I'm facing this issue in my project ?
