### ISSUE TITLE
http in DANGER_GITLAB_API_BASE_URL ignored

### ISSUE THREAD

**Issue by SvenMuc** [danger/swift#445]
I have a local installation of GitLab and therefore do not use any encryption. Danger JS had no issues with this setup.
danger swift ignores the http definition in DANGER_GITLAB_API_BASE_URL and changes the address to https.

How can I force the http connection?

# Environment Variables
``` bash
$ printenv
...
DANGER_GITLAB_API_BASE_URL=http://*****.local/api/v4
DANGER_GITLAB_API_TOKEN=*********
...
```

# danger-swift ci
``` bash
$ danger-swift ci
184Error:  FetchError: request to https://*****.local/api/v4/projects/******/merge_requests/21/changes failed, reason: connect ECONNREFUSED ******:443
185    at ClientRequest.<anonymous> (/snapshot/danger-js/node_modules/node-fetch/lib/index.js:1444:11)
186    at ClientRequest.emit (events.js:210:5)
187    at TLSSocket.socketErrorListener (_http_client.js:406:9)
188    at TLSSocket.emit (events.js:210:5)
189    at emitErrorNT (internal/streams/destroy.js:92:8)
190    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
191    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
192  message: 'request to https://****.local/api/v4/projects/******/merge_requests/21/changes failed, reason: connect ECONNREFUSED *****:443',
193  type: 'system',
194  errno: 'ECONNREFUSED',
195  code: 'ECONNREFUSED'
```

**Comment by f-meloni** [comment]
Danger-Swift uses Danger-JS under the hood to make all the requests to the various platforms (GitLab, GitHub, Bitbucket etc), so I think Danger-JS will need to support http connections in order to make it work
