### ISSUE TITLE
Error running danger-swift pr

### ISSUE THREAD

**Issue by rarias84** [danger/swift#557]
Running danger-swift pr with all the env configured I receive this response.

Response: {
  "error": "unauthorized_client",
  "error_description": "Invalid OAuth client credentials"
}
Error:  Error: 400 - Bad Request (Have you set DANGER_BITBUCKETCLOUD_USERNAME or DANGER_BITBUCKETCLOUD_OAUTH_KEY?)
    at throwIfNotOk (/Users/user/.nvm/versions/node/v18.4.0/lib/node_modules/danger/distribution/platforms/bitbucket_cloud/BitBucketCloudAPI.js:502:15)
    at BitBucketCloudAPI.<anonymous> (/Users/user/.nvm/versions/node/v18.4.0/lib/node_modules/danger/distribution/platforms/bitbucket_cloud/BitBucketCloudAPI.js:412:29)
    at step (/Users/user/.nvm/versions/node/v18.4.0/lib/node_modules/danger/distribution/platforms/bitbucket_cloud/BitBucketCloudAPI.js:44:23)
    at Object.next (/Users/user/.nvm/versions/node/v18.4.0/lib/node_modules/danger/distribution/platforms/bitbucket_cloud/BitBucketCloudAPI.js:25:53)
    at fulfilled (/Users/user/.nvm/versions/node/v18.4.0/lib/node_modules/danger/distribution/platforms/bitbucket_cloud/BitBucketCloudAPI.js:16:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by orta** [comment]
I think, right now, this is likely on you to figure out what's going on with your ENV unless others come and say they have the same problem
