### ISSUE TITLE
Cannot run danger-swift local

### ISSUE THREAD

**Issue by rarias84** [danger/swift#561]
I could run `swift run danger-swift local --base dev` without problems but now when I run the command I get the following

Error:  TypeError: Cannot read property 'metadata' of undefined
    at apiForDSL (/snapshot/danger-js/distribution/runner/jsonToDSL.js:133:78)
    at /snapshot/danger-js/distribution/runner/jsonToDSL.js:84:23
    at step (/snapshot/danger-js/distribution/runner/jsonToDSL.js:52:23)
    at Object.next (/snapshot/danger-js/distribution/runner/jsonToDSL.js:33:53)
    at /snapshot/danger-js/distribution/runner/jsonToDSL.js:27:71
    at new Promise (<anonymous>)
    at /snapshot/danger-js/distribution/runner/jsonToDSL.js:23:12
    at jsonToDSL (/snapshot/danger-js/distribution/runner/jsonToDSL.js:77:49)
    at /snapshot/danger-js/distribution/commands/utils/runDangerSubprocess.js:171:68
    at step (/snapshot/danger-js/distribution/commands/utils/runDangerSubprocess.js:44:23)

**Comment by f-meloni** [comment]
It seems this error is coming from Danger-JS 🤔

**Comment by rarias84** [comment]
I use danger version 11.2.1 and danger swift 3.15.0 .
I can see a danger-response.json but cannot see the report in the terminal just get the error above
