### ISSUE TITLE
ERROR: Failed to parse JSON: valueNotFound

### ISSUE THREAD

**Issue by kgrigsby59** [danger/swift#585]
Hello, I'm running Danger/swift as a GitHub action building an Xcode project. The build and test steps complete successfully and are outputting a Results.xcresult. The Danger steps runs after this. Danger is failing only for this PR. Others work fine.
```
Build complete! (7.33s)
ERROR: Failed to parse JSON: valueNotFound(Swift.KeyedDecodingContainer<Danger.GitHub.User.CodingKeys>, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "danger", intValue: nil), CodingKeys(stringValue: "github", intValue: nil), CodingKeys(stringValue: "reviews", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "user", intValue: nil)], debugDescription: "Cannot get keyed decoding container -- found null value instead.", underlyingError: nil))

ERROR: Dangerfile eval failed at Dangerfile.swift
ERROR: Could not get the results JSON file at /var/folders/67/gkms4rg94q71z22g0fv4p1rm0000gn/T/danger/1C82A6BB-0A4A-4A8C-AC0C-3970AC908619/danger-response.json

Failing the build, there is 1 fail.
Error:  TypeError: Cannot read property 'id' of null
    at /snapshot/danger-js/distribution/platforms/github/GitHubAPI.js:426:94
    at Array.map (<anonymous>)
    at /snapshot/danger-js/distribution/platforms/github/GitHubAPI.js:425:38
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

ℹ️  A new release of danger-swift is available: 3.15.0 -> 3.16.0

```

**Comment by kgrigsby59** [comment]
Reposted the PR and now it's working. 🤷🏻‍♂️
